CREATE TABLE Employees (
	Id INT NOT NULL,
	Name VARCHAR (25) NOT NULL,
	Salary INT NOT NULL,
	DeptId INT NOT NULL,

);

CREATE TABLE Department (
	DeptId INT NOT NULL,
	DeptName VARCHAR (25) NOT NULL,
);